server:
  port: 8080 #指定项目访问端口
  servlet:
    context-path: / #指定项目路径

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存，有利于开发阶段的调试
    prefix: classpath:/templates/ #指定页面的存放位置（默认）
    suffix: .html #指定页面的后缀（默认）
    encoding: utf-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html

  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动类
    url: jdbc:mysql://localhost:3306/fixedassets?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml目录
  type-aliases-package: com.gjs.fixedassets.entity #指定实体类的别名
  configuration:
    map-underscore-to-camel-case: true #驼峰命名和下划线命名相互转换

#添加mapper层的sql语句输出

logging:
  level:
    com.gjs.fixedassets: debug
    com.gjs.fixedassets.mapper: debug

#分页插件 pageHepler
pagehelper:
  helper-dialect: mysql #配置使用哪种数据库语言，不配置的话pageHelper也会自动检测
  resonable: true #配置分页参数合理化功能，默认是false。
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页；
  #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据。
  support-methods-arguments: true
  #支持通过Mapper接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。